#include "hyprland_shortcuts.h"

// Generated by wayland-scanner from hyprland-global-shortcuts-v1.xml.
// The header is emitted into CMAKE_CURRENT_BINARY_DIR.
#include "hyprland-global-shortcuts-client-protocol.h"

#include <dbus/dbus.h>
#include <glib.h>
#include <wayland-client.h>

#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

// ---------------------------------------------------------------------------
// State
// ---------------------------------------------------------------------------

struct ShortcutEntry {
  hyprland_global_shortcut_v1* obj;
  const char*                  id;   // points into kShortcutIds – stable lifetime
};

static struct {
  wl_display*                           display     = nullptr;
  wl_registry*                          registry    = nullptr;
  hyprland_global_shortcuts_manager_v1* manager     = nullptr;
  std::vector<ShortcutEntry>            shortcuts;
  std::string                           dbus_dest;
  std::string                           dbus_path;
  std::string                           dbus_iface;
  DBusConnection*                       dbus        = nullptr;
  GIOChannel*                           io_channel  = nullptr;
  guint                                 io_watch    = 0;
} g_state;

// ---------------------------------------------------------------------------
// Shortcut definitions – must match SystemWideShortcuts.shortcuts in Dart
// ---------------------------------------------------------------------------

static const char* kIds[]   = { "mute", "unmute", "toggle_mute" };
static const char* kDescs[] = {
  "Mute microphone",
  "Unmute microphone",
  "Toggle microphone mute",
};
static const int kCount = 3;

// ---------------------------------------------------------------------------
// Shortcut event handlers
// ---------------------------------------------------------------------------

static void on_shortcut_pressed(void*                        data,
                                hyprland_global_shortcut_v1* /*shortcut*/,
                                uint32_t /*tv_sec_hi*/,
                                uint32_t /*tv_sec_lo*/,
                                uint32_t /*tv_nsec*/) {
  const char* id = static_cast<const char*>(data);
  if (!g_state.dbus) return;

  // Call the D-Bus method on our own service – the Dart DBusObject
  // at /…/Shortcuts handles it and invokes the matching AppShortcut callback.
  DBusMessage* msg = dbus_message_new_method_call(
      g_state.dbus_dest.c_str(),
      g_state.dbus_path.c_str(),
      g_state.dbus_iface.c_str(),
      id);
  if (!msg) return;

  // Fire-and-forget; no reply needed.
  dbus_connection_send(g_state.dbus, msg, nullptr);
  dbus_connection_flush(g_state.dbus);
  dbus_message_unref(msg);
}

static void on_shortcut_released(void*, hyprland_global_shortcut_v1*,
                                  uint32_t, uint32_t, uint32_t) {
  // Not used.
}

static const hyprland_global_shortcut_v1_listener kShortcutListener = {
  .pressed  = on_shortcut_pressed,
  .released = on_shortcut_released,
};

// ---------------------------------------------------------------------------
// Wayland registry listener
// ---------------------------------------------------------------------------

static void on_registry_global(void* /*data*/, wl_registry* registry,
                                uint32_t name, const char* interface,
                                uint32_t /*version*/) {
  if (strcmp(interface,
             hyprland_global_shortcuts_manager_v1_interface.name) == 0) {
    g_state.manager =
        static_cast<hyprland_global_shortcuts_manager_v1*>(wl_registry_bind(
            registry, name,
            &hyprland_global_shortcuts_manager_v1_interface, 1));
  }
}

static void on_registry_global_remove(void*, wl_registry*, uint32_t) {}

static const wl_registry_listener kRegistryListener = {
  .global        = on_registry_global,
  .global_remove = on_registry_global_remove,
};

// ---------------------------------------------------------------------------
// GLib I/O watch – called on the main thread when Wayland data is ready
// ---------------------------------------------------------------------------

static gboolean on_wayland_readable(GIOChannel* /*channel*/,
                                     GIOCondition condition,
                                     gpointer /*data*/) {
  if (condition & (G_IO_ERR | G_IO_HUP)) {
    g_state.io_watch = 0;  // GLib removes the source for us
    return G_SOURCE_REMOVE;
  }
  // Safe single-threaded dispatch; we are on the GLib main loop.
  wl_display_dispatch(g_state.display);
  return G_SOURCE_CONTINUE;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

int hyprland_shortcuts_init(const char* app_id, const char* dbus_service) {
  // Build D-Bus address strings from the stable service name.
  // "chat.tungstn.app" → dest  = "chat.tungstn.app"
  //                    → path  = "/chat/tungstn/app/Shortcuts"
  //                    → iface = "chat.tungstn.app.Shortcuts"
  g_state.dbus_dest  = dbus_service;
  std::string path   = "/";
  for (char c : std::string(dbus_service)) path += (c == '.') ? '/' : c;
  path              += "/Shortcuts";
  g_state.dbus_path  = path;
  g_state.dbus_iface = std::string(dbus_service) + ".Shortcuts";

  // Open a secondary Wayland connection (separate from GTK's own connection).
  g_state.display = wl_display_connect(nullptr);
  if (!g_state.display) return 0;

  g_state.registry = wl_display_get_registry(g_state.display);
  wl_registry_add_listener(g_state.registry, &kRegistryListener, nullptr);
  wl_display_roundtrip(g_state.display);  // synchronously populate registry

  if (!g_state.manager) {
    // hyprland-global-shortcuts-v1 not advertised – not a Hyprland compositor.
    wl_registry_destroy(g_state.registry);
    wl_display_disconnect(g_state.display);
    g_state.display  = nullptr;
    g_state.registry = nullptr;
    return 0;
  }

  // Register each shortcut.  The compositor will associate a keybind via the
  // user's hyprland.conf, e.g.:
  //   bind = SUPER, M, global, chat.tungstn.app:toggle_mute
  for (int i = 0; i < kCount; i++) {
    hyprland_global_shortcut_v1* obj =
        hyprland_global_shortcuts_manager_v1_register_shortcut(
            g_state.manager,
            kIds[i],
            app_id,
            kDescs[i],
            "");  // trigger_description is informational only; compositor sets it
    hyprland_global_shortcut_v1_add_listener(
        obj, &kShortcutListener,
        const_cast<void*>(static_cast<const void*>(kIds[i])));
    g_state.shortcuts.push_back({obj, kIds[i]});
  }
  wl_display_flush(g_state.display);

  // Open a private D-Bus connection for the self-call back into Dart.
  // dbus_bus_get_private avoids sharing the connection with the dbus Dart
  // package which may have its own session connection.
  DBusError err;
  dbus_error_init(&err);
  g_state.dbus = dbus_bus_get_private(DBUS_BUS_SESSION, &err);
  if (dbus_error_is_set(&err)) {
    fprintf(stderr, "hyprland_shortcuts: D-Bus: %s\n", err.message);
    dbus_error_free(&err);
    // Non-fatal: shortcut presses will silently no-op until D-Bus is up.
  }

  // Watch the Wayland fd on the GLib main loop so event dispatch happens on
  // the main thread without an extra thread.
  int fd = wl_display_get_fd(g_state.display);
  g_state.io_channel = g_io_channel_unix_new(fd);
  g_state.io_watch   = g_io_add_watch(
      g_state.io_channel,
      static_cast<GIOCondition>(G_IO_IN | G_IO_ERR | G_IO_HUP),
      on_wayland_readable, nullptr);

  return 1;
}

void hyprland_shortcuts_cleanup(void) {
  if (g_state.io_watch) {
    g_source_remove(g_state.io_watch);
    g_state.io_watch = 0;
  }
  if (g_state.io_channel) {
    g_io_channel_unref(g_state.io_channel);
    g_state.io_channel = nullptr;
  }
  for (auto& e : g_state.shortcuts) {
    hyprland_global_shortcut_v1_destroy(e.obj);
  }
  g_state.shortcuts.clear();
  if (g_state.manager) {
    hyprland_global_shortcuts_manager_v1_destroy(g_state.manager);
    g_state.manager = nullptr;
  }
  if (g_state.registry) {
    wl_registry_destroy(g_state.registry);
    g_state.registry = nullptr;
  }
  if (g_state.dbus) {
    dbus_connection_close(g_state.dbus);
    dbus_connection_unref(g_state.dbus);
    g_state.dbus = nullptr;
  }
  if (g_state.display) {
    wl_display_disconnect(g_state.display);
    g_state.display = nullptr;
  }
}
